dataset:
  class: File
  path: ../../qubo_max_cut.jsonl

cut_dim: 10
enable_sparse_check: false
enable_iqm: true
enable_quantinuum_h2: false
enable_quantinuum_h2e: false
iqm_real_jobs: "1"
solutions_store_dir: solutions
# quantinuum_h2_real_jobs: "1"
# quantinuum_h2e_real_jobs: "1"
